// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;

import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGW9_h61iItwIOAHDG16hmO2SS_ayLO8',
    appId: '1:471133590366:web:dd643ac25405a4cdcfb5cf',
    messagingSenderId: '471133590366',
    projectId: 'todomateapp-3423a',
    authDomain: 'todomateapp-3423a.firebaseapp.com',
    storageBucket: 'todomateapp-3423a.appspot.com',
    measurementId: 'G-T3S3Y32X0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8mZnUsBp1BDVpXFwPKqLStYKMYyWuWeA',
    appId: '1:471133590366:android:f475937e51194b5fcfb5cf',
    messagingSenderId: '471133590366',
    projectId: 'todomateapp-3423a',
    storageBucket: 'todomateapp-3423a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEByTYurOiiZEKMpmp-ZABPnnhxe5CeM',
    appId: '1:471133590366:ios:18dcdec765cd3238cfb5cf',
    messagingSenderId: '471133590366',
    projectId: 'todomateapp-3423a',
    storageBucket: 'todomateapp-3423a.appspot.com',
    iosClientId:
        '471133590366-j073ql9q3pa6mu8v064fs0k5ga2vrf3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoMateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWEByTYurOiiZEKMpmp-ZABPnnhxe5CeM',
    appId: '1:471133590366:ios:18dcdec765cd3238cfb5cf',
    messagingSenderId: '471133590366',
    projectId: 'todomateapp-3423a',
    storageBucket: 'todomateapp-3423a.appspot.com',
    iosClientId:
        '471133590366-j073ql9q3pa6mu8v064fs0k5ga2vrf3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoMateApp',
  );
}
